name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen? Note you can attach files here.
      placeholder: 
      value: 
    validations:
      required: true
  - type: dropdown
    id: app
    attributes:
      label: Application
      description: Which application experienced a bug?
      options:
        - DD Toolbox
        - DSI-2
        - DSI-3
    validations:
      required: true
  - type: input
    id: app-version
    attributes:
      label: Application Version
      description: What version of our software are you running?
    validations:
      required: true
  - type: dropdown
    id: module
    attributes:
      label: Module
      description: Which Toolbox module experienced a bug?
      options:
        - DD Box Calculator
        - Power Calculator
        - Tone Generator
    validations:
      required: false
  - type: dropdown
    id: device-os
    attributes:
      label: What device OS are you using?
      multiple: false
      options:
        - Apple
        - Android
        - Mac (DSI only)
        - Windows (DSI only)
    validations:
      required: true
  - type: input
    id: os-version
    attributes:
      label: What device OS version are you using?
      description: Input your specific device OS version
    validations:
      required: true
  - type: input
    id: make-model
    attributes:
      label: What make and model is your device?
      description: Input your specific device make and model
    validations:
      required: true
  - type: input
    id: country
    attributes:
      label: What country is your device set to?
      description: Input your device country
    validations:
      required: true
  - type: input
    id: language
    attributes:
      label: What language is your device set to?
      description: Input your device language
    validations:
      required: true
  - type: dropdown
    id: connectivity
    attributes:
      label: Were you connected to the internet?
      description: At the time of the issue, were you connected to the internet?
      multiple: false
      options:
        - 'Yes'
        - 'No'
    validations:
      required: true
