name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: 
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 2.x
        - 1.x
    validations:
      required: true
  - type: dropdown
    id: device-os
    attributes:
      label: What device OS are you using?
      multiple: false
      options:
        - Apple
        - Android
    validations:
      required: true
  - type: input
    id: make-model
    attributes:
      label: What make and model is your device?
      description: Input your specific device make and model
    validations:
      required: true
  - type: input
    id: country
    attributes:
      label: What country are you in?
      description: Please enter your country
      validations:
      required: true
  - type: input
    id: language
    attributes:
      label: What is your device's default language?
      description: Input your devices default language
    validations:
      required: true
  - type: dropdown
    id: connectivity
    attributes:
      label: Were you connected to the internet?
      description: At the time of the issue, were you connected to the internet?
      multiple: false
      options:
        - 'Yes'
        - 'No'
    validations:
      required: true
