name: Enhancement Request
description: File an enhancement request
title: "[Enhancement]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us improve our products!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: true
  - type: textarea
    id: request-description
    attributes:
      label: Describe Your Enhancement Request. If this is a language request, please note that here. Please also note if you're willing to help translate.
      description: Note you can attach files here.
      placeholder: 
      value: 
    validations:
      required: true
  - type: dropdown
    id: app
    attributes:
      label: Application
      description: Which application do you want enhanced?
      options:
        - DD Toolbox
        - DSI-2
        - DSI-3
    validations:
      required: true
  - type: dropdown
    id: module
    attributes:
      label: Module
      description: Which Toolbox module do you want enhanced?
      options:
        - App Wide
        - DD Box Calculator
        - Power Calculator
        - Tone Generator
        - New module suggestion
    validations:
      required: false
  - type: dropdown
    id: device-os
    attributes:
      label: What device OS are you using?
      multiple: false
      options:
        - Apple
        - Android
        - Mac (DSI only)
        - Windows (DSI only)
    validations:
      required: true
  - type: input
    id: os-version
    attributes:
      label: What device OS version are you using?
      description: Input your specific device OS version
    validations:
      required: true
  - type: input
    id: country
    attributes:
      label: What country is your device set to?
      description: Input your device country
    validations:
      required: true
  - type: input
    id: language
    attributes:
      label: What language is your device set to?
      description: Input your device language
    validations:
      required: true
